- name: Deploy javadoc to Github Pages
    uses: dev-vince/actions-publish-javadoc@v1.0.1
    with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: "21" # Replace with your java version. Default is 17
